import { test } from 'node:test';
import assert from 'node:assert/strict';
import { browserBudget } from '../src/seed/core/log';
import { verifyPassword, readSession, createSession } from '../src/admin/auth';
import { nextCronRunMs, cronSummary } from '../src/admin/cron';
import { cityBbox, nearestCity } from '../src/admin/cities';
import { eventsSql } from '../src/admin/queries';
import { ProviderId } from '../src/seed/core/types';

test('browserBudget: sums browser_ms for current month', async () => {
  // Fake D1 with two rows; one inside month (now), one old.
  const rows = [
    { total: 5 * 3_600_000 },   // this month
    { total: 5 * 3_600_000 },   // this month (second row)
  ];
  const env = {
    BROWSER: {},
    DB: {
      prepare: () => ({
        bind: () => ({
          first: async () => ({ total: rows.reduce((a, r) => a + r.total, 0) }),
        }),
      }),
    },
  } as unknown as Env;
  const b = await browserBudget(env);
  assert.ok(b);
  assert.equal(b.monthMs, 10 * 3_600_000);
  assert.equal(b.exceeded, false); // == limit, not > limit
});

test('admin verifyPassword: correct/incorrect hash', async () => {
  // hash of "test-password-123" (generated by admin/scripts/hash-admin-password.mjs)
  const hash = '9ab199cca9f06e22a8b33d342ba07d06:100000:54a71ff74f0e9427b185118f6df65ed55394b46609ea45202d90a7389f83aa65';
  assert.equal(await verifyPassword('test-password-123', hash), true);
  assert.equal(await verifyPassword('wrong', hash), false);
  assert.equal(await verifyPassword('x', 'not-a-hash'), false);
});

test('admin session: valid cookie, expired cookie, tampered cookie', async () => {
  const env = { ADMIN_COOKIE_SECRET: 'test-cookie-secret' } as unknown as Env;
  const cookie = await createSession(env);
  assert.ok(cookie);
  const session = await readSession(env, cookie);
  assert.ok(session);
  assert.equal(session!.sub, 'admin');
  assert.ok(session!.exp > Date.now());

  // tampered payload -> rejected
  assert.equal(await readSession(env, cookie + 'x'), null);
  // wrong secret -> rejected
  const otherEnv = { ADMIN_COOKIE_SECRET: 'different' } as unknown as Env;
  assert.equal(await readSession(otherEnv, cookie), null);
  // missing secret -> rejected
  assert.equal(await readSession({} as Env, cookie), null);
});

test('cron: nextCronRunMs is in the future, summary non-empty', () => {
  const next = nextCronRunMs('0 2 * * *');
  assert.ok(next);
  assert.ok(next > Date.now());
  assert.equal(nextCronRunMs('bad'), null);
  assert.ok(cronSummary().length > 0);
});

test('cities: bbox is centered and nearestCity works', () => {
  const bbox = cityBbox('poznan');
  assert.ok(bbox);
  assert.ok(bbox.swLat < bbox.neLat && bbox.swLng < bbox.neLng);
  // Poznań center is inside its own bbox
  assert.ok(bbox.swLat <= 52.4064 && 52.4064 <= bbox.neLat);
  assert.equal(nearestCity(52.4064, 16.9252), 'Poznań');
  assert.equal(cityBbox('nope'), null);
});

test('eventsSql: city filter adds bbox binds, date range uses event_date', () => {
  const { sql, binds } = eventsSql({ cityId: 'warszawa', source: ProviderId.GOING, status: null, from: '2026-08-16', to: '2026-08-16', tag: null, geo: null, fromMs: null, toMs: null, limit: 50 });
  assert.ok(sql.includes('p.lat BETWEEN'));
  assert.ok(sql.includes('p.event_date'));
  assert.ok(sql.includes('LIMIT ?'));
  assert.ok(sql.includes('OFFSET ?'));
  assert.ok(binds.length >= 4);
  assert.equal(binds[binds.length - 2], 50);
});

test('eventsSql: geo=default filters to city bbox centers (seed fallback pins)', () => {
  const { sql } = eventsSql({ cityId: null, source: null, status: null, from: null, to: null, tag: null, geo: 'default', fromMs: null, toMs: null, limit: 50 });
  assert.ok(sql.includes('ABS(p.lat -'));
  assert.ok(sql.includes('ABS(p.lng -'));
  const { sql: other } = eventsSql({ cityId: null, source: null, status: null, from: null, to: null, tag: null, geo: 'default', fromMs: null, toMs: null, limit: 50 });
  assert.equal(other, sql, 'geo clause is deterministic');
});
