// Builds src/admin/ui/templates.gen.ts from src/admin/ui/templates/*.html.
// The generated module is COMMITTED, so deploy needs no build step.
// Run `npm run gen:templates` after editing any template.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const tplDir = join(here, '..', 'src', 'admin', 'ui', 'templates');
const outFile = join(here, '..', 'src', 'admin', 'ui', 'templates.gen.ts');

const files = readdirSync(tplDir).filter((f) => f.endsWith('.html'));
const lines: string[] = [
  '// AUTO-GENERATED by scripts/gen-templates.ts — do not edit by hand.',
  '// Run: npm run gen:templates after editing src/admin/ui/templates/*.html',
  'export const TEMPLATES: Record<string, string> = {',
];
for (const f of files.sort()) {
  const raw = readFileSync(join(tplDir, f), 'utf8');
  const body = raw.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  lines.push(`  ${JSON.stringify(f.replace(/\.html$/, ''))}: \`${body}\`,`);
}
lines.push('};');
writeFileSync(outFile, lines.join('\n') + '\n');
console.log(`templates.gen.ts written (${files.length} templates)`);
