// AUTO-GENERATED by scripts/gen-templates.ts — do not edit by hand.
// Run: npm run gen:templates after editing src/admin/ui/templates/*.html
export const TEMPLATES: Record<string, string> = {
  "alert": `<div class="alert alert-{{{kind}}} {{{class}}} mb-3" role="alert">
  {{{content}}}
</div>
`,
  "avatar": `<span class="avatar {{{class}}}">{{{content}}}</span>
`,
  "badge": `<span class="badge {{{class}}}">{{{text}}}</span>
`,
  "bars": `<div class="d-flex align-items-center mb-2 gap-2">
  <span class="text-secondary">{{{label}}}</span>
  <div class="progress flex-grow-1 progress-sm"><div class="progress-bar" style="width:{{{width}}}%"></div></div>
  <span class="text-muted text-end">{{{value}}}</span>
</div>
`,
  "card-header": `<div class="card-header">
  <h3 class="card-title">{{{title}}}</h3>
  {{{actions}}}
</div>
`,
  "card": `<div class="card {{{class}}}">
  {{{header}}}
  {{{body}}}
  {{{footer}}}
</div>
`,
  "dropdown": `<div class="dropdown {{{class}}}">
  <button class="btn btn-action dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" title="{{{title}}}">
    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><use href="#icon-more-horizontal"/></svg>
  </button>
  <div class="dropdown-menu dropdown-menu-end">
    {{{items}}}
  </div>
</div>
`,
  "empty": `<div class="empty">
  <div class="empty-icon">{{{icon}}}</div>
  <p class="empty-title">{{{title}}}</p>
  <p class="empty-subtitle text-secondary">{{{subtitle}}}</p>
  {{{action}}}
</div>
`,
  "filter-select": `<div class="col-6 col-md-{{{span}}}">
  <label class="form-label">{{{label}}}</label>
  <select name="{{{name}}}" class="form-select" onchange="this.form.submit()">{{{options}}}</select>
</div>
`,
  "list-group": `<div class="list-group {{{class}}} list-group-hoverable">
  {{{items}}}
</div>
`,
  "login": `<div class="container-tight py-5">
  <div class="card card-md"><div class="card-body p-4">
    <h2 class="card-title mb-1">PanPeryskop · Admin</h2>
    <p class="text-secondary mb-3">Zaloguj się (sesja 72h)</p>
    <form method="post" action="/admin/login">
      <div class="mb-3"><input type="password" name="password" class="form-control" placeholder="Hasło" required autofocus /></div>
      <button class="btn btn-primary w-100" type="submit">Zaloguj</button>
    </form>
  </div></div>
</div>
`,
  "modal": `<div class="modal fade" id="{{{id}}}" tabindex="-1">
  <div class="modal-dialog {{{dialogCls}}}">
    <div class="modal-content">
      {{{status}}}
      {{{content}}}
    </div>
  </div>
</div>
`,
  "page-header": `<div class="page-header d-print-none {{{class}}}">
  <div class="row align-items-center">
    <div class="col">
      <div class="page-pretitle">{{{pretitle}}}</div>
      <h2 class="page-title">{{{title}}}</h2>
      {{{subtitle}}}
    </div>
    <div class="col-auto ms-auto d-print-none">
      {{{actions}}}
    </div>
  </div>
</div>
`,
  "pager": `<div class="d-flex justify-content-between align-items-center {{{class}}} flex-wrap gap-2">
  <span class="text-secondary">{{{count}}}</span>
  {{{pagination}}}
</div>
`,
  "pagination": `<nav><ul class="pagination pagination-sm mb-0">{{{items}}}</ul></nav>
`,
  "segmented": `<div class="btn-group btn-group-segmented {{{class}}}" role="group">
  {{{items}}}
</div>
`,
  "table": `<div class="card {{{class}}}">
  {{{header}}}
  <div class="table-responsive"><table class="table table-vcenter card-table">
    {{{head}}}
    <tbody>{{{rows}}}</tbody>
  </table></div>
  {{{footer}}}
</div>
`,
  "timeline-item": `<div class="timeline-item">
  <div class="timeline-icon">{{{icon}}}</div>
  <div class="timeline-content">
    <div class="text-secondary">{{{label}}}</div>
    <div class="fw-bold">{{{value}}}</div>
    {{{hint}}}
  </div>
</div>
`,
  "timeline": `<div class="timeline">
  {{{items}}}
</div>
`,
  "toast-container": `<div class="toast-container position-fixed bottom-0 end-0 p-3" id="ppToastWrap" style="z-index:1055"></div>
`,
};
