name: PanPeryskop

settings:
  MARKETING_VERSION: "1.1"
  CURRENT_PROJECT_VERSION: 8
  DEVELOPMENT_TEAM: "3UKH2QRFKZ"
  SWIFT_VERSION: "6.0"
  INFOPLIST_KEY_CFBundleDisplayName: "Pan Peryskop"

options:
  developmentLanguage: pl
  bundleIdPrefix: pl.piszeprogramy
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

packages:
  LazyPager:
    path: vendor/LazyPager
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.2.0
  FYVideoCompressor:
    url: https://github.com/T2Je/FYVideoCompressor
    from: 0.0.6
  YPImagePicker:
    path: vendor/YPImagePicker

targets:
  PanPeryskop:
    type: application
    platform: iOS
    sources:
      - path: PanPeryskop
    dependencies:
      - package: LazyPager
        product: LazyPager
      - package: KeychainAccess
        product: KeychainAccess
      - package: FYVideoCompressor
        product: FYVideoCompressor
      - package: YPImagePicker
        product: YPImagePicker
    info:
      path: PanPeryskop/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.panperyskop
            CFBundleURLSchemes:
              - panperyskop
        BGTaskSchedulerPermittedIdentifiers:
          - com.panperyskop.refresh.media
        UIBackgroundModes:
          - fetch
        ITSAppUsesNonExemptEncryption: false
    entitlements:
      path: PanPeryskop/SignInWithApple.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    scheme:
      configVariants: []
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: pl.piszeprogramy.panperyskop
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: ["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"]
        INFOPLIST_KEY_NSCameraUsageDescription: "Potrzebujemy dostępu do aparatu, aby nagrywać treści."
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "Zapisujemy kopię zapasową nagrania w Twojej galerii."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Potrzebujemy dostępu do galerii, aby wybierać zdjęcia i filmy."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Potrzebujemy mikrofonu do nagrywania filmów."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Używamy Twojej lokalizacji, aby pokazać Twoją pozycję na mapie i przypisywać treści do miejsc."
        GENERATE_INFOPLIST_FILE: YES
